apiVersion: v2
name: ecommerce
description: Umbrella chart for ecommerce platform
type: application
version: 0.1.0

dependencies:
  - name: backend
    version: 0.1.0
    repository: "file://../backend"

  - name: frontend
    version: 0.1.0
    repository: "file://../frontend"

  - name: mysql
    version: 0.1.0
    repository: "file://../mysql"

